const events = [
  {
    title: "Tech Conference 2025",
    venue: "Convention Center Hall A",
    date: "2025-05-15",
    guestlist: [
      "John Smith",
      "Sarah Johnson",
      "Mike Chen",
      "Alicia Rodriguez",
      "Thomas Baker",
      "Kelly Wong",
    ],
  },
  {
    title: "Jazz Night",
    venue: "Blue Note Club",
    date: "2025-04-20",
    guestlist: [
      "Emma Davis",
      "Robert Wilson",
      "Lisa Anderson",
      "David Kim",
      "Michelle Carter",
      "James Peterson",
    ],
  },
  {
    title: "Charity Gala",
    venue: "Grand Hotel Ballroom",
    date: "2025-06-10",
    guestlist: [
      "Dr. Emily Brown",
      "James Taylor",
      "Patricia Lee",
      "William Chen",
      "Sophie Martinez",
      "Edward Grant",
    ],
  },
  {
    title: "Art Exhibition Opening",
    venue: "Modern Art Gallery",
    date: "2025-04-25",
    guestlist: [
      "Olivia Grant",
      "Henry Sullivan",
      "Grace Thompson",
      "Alexander White",
      "Julia Brooks",
      "Nathan Reed",
    ],
  },
  {
    title: "Business Networking Mixer",
    venue: "Skyline Rooftop Lounge",
    date: "2025-05-01",
    guestlist: [
      "Richard Parker",
      "Jennifer Lynn",
      "Carlos Mendez",
      "Rachel Foster",
      "Daniel Kim",
      "Laura Bennett",
    ],
  },
  {
    title: "Film Festival Premiere",
    venue: "Starlight Cinema",
    date: "2025-07-12",
    guestlist: [
      "Tom Harrison",
      "Nicole Evans",
      "Samuel Ortiz",
      "Katherine Lee",
      "Peter Nguyen",
      "Rebecca Stone",
    ],
  },
  {
    title: "Science Symposium",
    venue: "University Lecture Hall",
    date: "2025-05-22",
    guestlist: [
      "Dr. Alan Foster",
      "Maria Gonzalez",
      "Philip Moore",
      "Linda Chen",
      "Brian Patel",
      "Sandra Hill",
    ],
  },
  {
    title: "Food & Wine Tasting",
    venue: "Vineyard Estate",
    date: "2025-06-28",
    guestlist: [
      "Anthony Russo",
      "Claire Simmons",
      "George Baker",
      "Vanessa Lopez",
      "Michael Ward",
      "Ellen Price",
    ],
  },
  {
    title: "Fashion Show Spring Collection",
    venue: "Metropolitan Event Center",
    date: "2025-04-30",
    guestlist: [
      "Isabella Ross",
      "Lucas Bennett",
      "Sophie Clark",
      "Gabriel Silva",
      "Emma Thompson",
      "Ryan Cooper",
    ],
  },
  {
    title: "Gaming Tournament",
    venue: "E-Sports Arena",
    date: "2025-07-05",
    guestlist: [
      "Tyler Jackson",
      "Amy Zhang",
      "Chris Morgan",
      "Jessica Park",
      "Ethan Lee",
      "Brandon Scott",
    ],
  },
];

export default events;
